FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/stock-worker ./cmd/stock-worker

FROM scratch
COPY --from=builder /app/stock-worker /stock-worker
CMD ["/stock-worker"]