// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/I000000/InventoryManagement/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// EventProducer is an autogenerated mock type for the EventProducer type
type EventProducer struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *EventProducer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendStockReservedEvent provides a mock function with given fields: ctx, event
func (_m *EventProducer) SendStockReservedEvent(ctx context.Context, event domain.StockReservedEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SendStockReservedEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.StockReservedEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventProducer creates a new instance of EventProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventProducer {
	mock := &EventProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
