// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/I000000/InventoryManagement/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ReserveLogRepository is an autogenerated mock type for the ReserveLogRepository type
type ReserveLogRepository struct {
	mock.Mock
}

// GetRecent provides a mock function with given fields: ctx, limit
func (_m *ReserveLogRepository) GetRecent(ctx context.Context, limit int) ([]domain.ReserveLogEntry, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecent")
	}

	var r0 []domain.ReserveLogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.ReserveLogEntry, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.ReserveLogEntry); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReserveLogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, productID, quantity, requestID, userID, status, errMsg
func (_m *ReserveLogRepository) Insert(ctx context.Context, productID string, quantity int, requestID string, userID string, status string, errMsg *string) error {
	ret := _m.Called(ctx, productID, quantity, requestID, userID, status, errMsg)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string, string, string, *string) error); ok {
		r0 = rf(ctx, productID, quantity, requestID, userID, status, errMsg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReserveLogRepository creates a new instance of ReserveLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReserveLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReserveLogRepository {
	mock := &ReserveLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
