// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/I000000/InventoryManagement/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ReserveService is an autogenerated mock type for the ReserveService type
type ReserveService struct {
	mock.Mock
}

// Reserve provides a mock function with given fields: ctx, req
func (_m *ReserveService) Reserve(ctx context.Context, req domain.ReserveRequest) (domain.ReserveResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Reserve")
	}

	var r0 domain.ReserveResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ReserveRequest) (domain.ReserveResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ReserveRequest) domain.ReserveResponse); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.ReserveResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ReserveRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReserveService creates a new instance of ReserveService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReserveService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReserveService {
	mock := &ReserveService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
